### Here we are using an Autoencoder to encode the digits 1 and 2 and we indivisually make the classes for the encoder and the decoder and then we concatenate both the functions later. 

In [2]:
import keras
from keras.layers import Input, Dense
from keras.models import Model
from keras.callbacks import TensorBoard
import numpy as np 
from tensorflow import set_random_seed
import os

In [ ]:
def seedy(s):
    np.random.seed(s)
    set_random_seed(s)

class AutoEncoder:
    def __init__(self, encoding_dim=3):
        self.encoding_dim = encoding_dim
        r = lambda: np.random.randint(1, 3)
        self.x = np.array([[r(),r(),r()] for _ in range(1000)])
        print(self.x)

    def _encoder(self):
        inputs = Input(shape=(self.x[0].shape))
        encoded = Dense(self.encoding_dim, activation='relu')(inputs)
        model = Model(inputs, encoded)
        self.encoder = model
        return model

    def _decoder(self):
        inputs = Input(shape=(self.encoding_dim,))
        decoded = Dense(3)(inputs)
        model = Model(inputs, decoded)
        self.decoder = model
        return model

    def encoder_decoder(self):
        ec = self._encoder()
        dc = self._decoder()
        
        inputs = Input(shape=self.x[0].shape)
        ec_out = ec(inputs)
        dc_out = dc(ec_out)
        model = Model(inputs, dc_out)
        
        self.model = model
        return model

    def fit(self, batch_size=10, epochs=300):
        self.model.compile(optimizer='sgd', loss='mse')
        log_dir = './log/'
        tbCallBack = keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=0, write_graph=True, write_images=True)
        self.model.fit(self.x, self.x,
                        epochs=epochs,
                        batch_size=batch_size,
                        callbacks=[tbCallBack])

    def save(self):
        if not os.path.exists(r'./weights'):
            os.mkdir(r'./weights')
        else:
            self.encoder.save(r'./weights/encoder_weights.h5')
            self.decoder.save(r'./weights/decoder_weights.h5')
            self.model.save(r'./weights/ae_weights.h5')
        

if __name__ == '__main__':
    seedy(2)
    ae = AutoEncoder(encoding_dim=2)
    ae.encoder_decoder()
    ae.fit(batch_size=50, epochs=300)
    ae.save()


[[1 2 2]
 [1 1 2]
 [1 2 1]
 ...
 [1 1 2]
 [1 1 2]
 [2 1 1]]
Epoch 1/300
1000/1000 [==============================] - 0s 328us/step - loss: 1.7200
Epoch 2/300
1000/1000 [==============================] - 0s 78us/step - loss: 0.4854
Epoch 3/300
1000/1000 [==============================] - 0s 94us/step - loss: 0.3288
Epoch 4/300
1000/1000 [==============================] - 0s 94us/step - loss: 0.2914
Epoch 5/300
1000/1000 [==============================] - 0s 78us/step - loss: 0.2751
Epoch 6/300
1000/1000 [==============================] - 0s 78us/step - loss: 0.2634
Epoch 7/300
1000/1000 [==============================] - 0s 94us/step - loss: 0.2538
Epoch 8/300
1000/1000 [==============================] - ETA: 0s - loss: 0.248 - 0s 47us/step - loss: 0.2455
Epoch 9/300
1000/1000 [==============================] - 0s 94us/step - loss: 0.2385
Epoch 10/300
1000/1000 [==============================] - 0s 78us/step - loss: 0.2323
Epoch 11/300
1000/1000 [==============================] - 0s 78u

### Check that the model.fit(x,x), ie the inputs and the outputs are the same in an Autoencoder.

In [7]:
from keras.models import load_model
import numpy as np

encoder = load_model(r'./weights/encoder_weights.h5')
decoder = load_model(r'./weights/decoder_weights.h5')

inputs = np.array([[1,7,3]])
x = encoder.predict(inputs)
y = decoder.predict(x)

print('Input: {}'.format(inputs))
print('Encoded: {}'.format(x))
print('Decoded: {}'.format(y))


Input: [[1 7 3]]
Encoded: [[0.       4.185444]]
Decoded: [[3.5106544 3.6673677 3.56367  ]]
