In [1]:
import os
import random
from glob import glob

import cv2
import numpy as np
import matplotlib.pyplot as plt
from keras import preprocessing

%matplotlib inline

Using TensorFlow backend.


In [2]:
class_names = ['WATCH', 'PHONE']

In [19]:
camera = cv2.VideoCapture(0)
raw_frames_type_1 = []
raw_frames_type_2 = []

while(True):
    # read a new frame
    _, frame = camera.read()
    
    # flip the frame
    frame = cv2.flip(frame, 1)

    # add rectangle
    cv2.rectangle(frame, (200, 110), (450, 350), (0, 255, 0), 2)
    
    # show the frame
    cv2.imshow("Capturing frames", frame)

    key = cv2.waitKey(1)

    # quit camera if 'q' key is pressed
    if key & 0xFF == ord("q"):
        break
    elif key & 0xFF == ord("1"):
    # save the frame
        raw_frames_type_1.append(frame)
        print('1 key pressed - saved TYPE_1 frame')
    elif key & 0xFF == ord("2"):
        # save the frame
        raw_frames_type_2.append(frame)
        print('2 key pressed - Saved TYPE_2 frame')
    
camera.release()
cv2.destroyAllWindows()

2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame
2 key pressed - Saved TYPE_2 frame


In [20]:
save_width = 399
save_height = 399
for i in range(1, 3):
    name = 'D:/PROJECT/images_type_{}'.format(i)
    os.makedirs(name, exist_ok=True)

In [21]:
for i, frame in enumerate(raw_frames_type_1):
    roi = frame[110+2:350-2, 200+2:450-2]
    roi = cv2.cvtColor(roi, cv2.COLOR_BGR2RGB)
    roi = cv2.resize(roi, (save_width, save_height))
    cv2.imwrite('D:/PROJECT/images_type_1/{}.png'.format(i), cv2.cvtColor(roi,cv2.COLOR_BGR2RGB))

for i, frame in enumerate(raw_frames_type_2):
    roi = frame[110+2:350-2, 200+2:450-2]
    roi = cv2.cvtColor(roi, cv2.COLOR_BGR2RGB)
    roi = cv2.resize(roi, (save_width, save_height))
    cv2.imwrite('D:/PROJECT/images_type_2/{}.png'.format(i), cv2.cvtColor(roi,cv2.COLOR_BGR2RGB))

In [22]:
width = 96
height = 96

In [23]:
import os
import random
from glob import glob
from PIL import Image
import matplotlib.pyplot as plt
from keras import preprocessing

In [24]:
def load_images(base_path):
    images = []
    path = os.path.join(base_path, '*.png')
    for image_path in glob(path):
        image = preprocessing.image.load_img(image_path,
                                             target_size=(width, height))
        x = preprocessing.image.img_to_array(image)

        images.append(x)
    return images

In [25]:
images_type_1 = load_images('D:/PROJECT/images_type_1')
images_type_2 = load_images('D:/PROJECT/images_type_2')

In [26]:
X_type_1 = np.array(images_type_1)
X_type_2 = np.array(images_type_2)

In [27]:
print(X_type_1.shape)
print(X_type_2.shape)

(10, 96, 96, 3)
(10, 96, 96, 3)


In [28]:
X = np.concatenate((X_type_1, X_type_2), axis=0)
X.shape

(20, 96, 96, 3)

In [29]:
X


array([[[[120., 128., 134.],
         [118., 128., 131.],
         [119., 129., 132.],
         ...,
         [163., 167., 170.],
         [166., 167., 168.],
         [164., 163., 177.]],

        [[120., 130., 134.],
         [116., 129., 130.],
         [118., 128., 135.],
         ...,
         [158., 173., 162.],
         [161., 172., 163.],
         [162., 169., 171.]],

        [[117., 130., 131.],
         [115., 128., 132.],
         [118., 127., 129.],
         ...,
         [155., 171., 165.],
         [159., 170., 168.],
         [162., 169., 164.]],

        ...,

        [[ 79.,  80.,  86.],
         [ 90.,  90.,  94.],
         [104., 106., 110.],
         ...,
         [ 19.,  22.,  35.],
         [ 15.,  20.,  28.],
         [  9.,  17.,  21.]],

        [[ 85.,  95.,  89.],
         [ 78.,  82.,  84.],
         [ 93.,  89., 103.],
         ...,
         [ 13.,  20.,  32.],
         [ 18.,  21.,  29.],
         [ 16.,  21.,  21.]],

        [[ 97., 105., 110.],
       

In [30]:
X = X / 255.0

X.shape

(20, 96, 96, 3)

In [83]:
X

array([[[[0.14901961, 0.2       , 0.2       ],
         [0.14901961, 0.2       , 0.19607843],
         [0.10980392, 0.21960784, 0.16862746],
         ...,
         [0.1254902 , 0.1764706 , 0.15294118],
         [0.12156863, 0.20392157, 0.12156863],
         [0.12156863, 0.21960784, 0.12941177]],

        [[0.16470589, 0.22745098, 0.19215687],
         [0.15686275, 0.20392157, 0.2       ],
         [0.15294118, 0.19607843, 0.21960784],
         ...,
         [0.14901961, 0.15686275, 0.1764706 ],
         [0.13333334, 0.1882353 , 0.16862746],
         [0.08235294, 0.14509805, 0.11764706]],

        [[0.14509805, 0.23529412, 0.19215687],
         [0.1882353 , 0.23529412, 0.2       ],
         [0.17254902, 0.23137255, 0.19607843],
         ...,
         [0.16078432, 0.19215687, 0.1764706 ],
         [0.13333334, 0.1764706 , 0.19607843],
         [0.12156863, 0.16470589, 0.18431373]],

        ...,

        [[0.09803922, 0.24705882, 0.21960784],
         [0.16078432, 0.21568628, 0.23529412]

In [33]:
from keras.utils import to_categorical

y_type_1 = [0 for item in enumerate(X_type_1)]
y_type_2 = [1 for item in enumerate(X_type_2)]


y = np.concatenate((y_type_1, y_type_2), axis=0)

y = to_categorical(y, num_classes=len(class_names))

print(y.shape)

(20, 2)


In [34]:
y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [35]:
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Flatten, Dense
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import Adam

In [36]:
conv_1 = 16
conv_1_drop = 0.2
conv_2 = 32
conv_2_drop = 0.2
dense_1_n = 1024
dense_1_drop = 0.2
dense_2_n = 512
dense_2_drop = 0.2
lr = 0.001

epochs = 30
batch_size = 32
color_channels = 1

def build_model(conv_1_drop=conv_1_drop, conv_2_drop=conv_2_drop,
                dense_1_n=dense_1_n, dense_1_drop=dense_1_drop,
                dense_2_n=dense_2_n, dense_2_drop=dense_2_drop,
                lr=lr):
    model = Sequential()

    model.add(Convolution2D(conv_1, (3, 3),
                            input_shape=X.shape[1:],
                            activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(conv_1_drop))

    model.add(Convolution2D(conv_2, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(conv_2_drop))
        
    model.add(Flatten())
        
    model.add(Dense(dense_1_n, activation='relu'))
    model.add(Dropout(dense_1_drop))

    model.add(Dense(dense_2_n, activation='relu'))
    model.add(Dropout(dense_2_drop))

    model.add(Dense(len(class_names), activation='softmax'))

    model.compile(loss='categorical_crossentropy',
                  optimizer=Adam(lr=lr),
                  metrics=['accuracy'])

    return model

In [37]:
import numpy as np
np.random.seed(1) 
# for reproducibility

# model with base parameters
model = build_model()

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 94, 94, 16)        448       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 47, 47, 16)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 47, 47, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 45, 45, 32)        4640      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 22, 22, 32)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 22, 22, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 15488)             0         
__________

In [38]:
epochs = 6

In [39]:
model.fit(X, y, epochs=epochs)

Epoch 1/6
20/20 [==============================] - 6s 286ms/step - loss: 0.6804 - acc: 0.4500
Epoch 2/6
20/20 [==============================] - 2s 77ms/step - loss: 0.2603 - acc: 0.9000
Epoch 3/6
20/20 [==============================] - 1s 63ms/step - loss: 6.2848 - acc: 0.5000
Epoch 4/6
20/20 [==============================] - 1s 55ms/step - loss: 0.0905 - acc: 0.9500
Epoch 5/6
20/20 [==============================] - 1s 48ms/step - loss: 0.7673 - acc: 0.5500
Epoch 6/6
20/20 [==============================] - 1s 45ms/step - loss: 0.0564 - acc: 1.0000


In [40]:
import time

# get the reference to the webcam
camera = cv2.VideoCapture(0)


while(True):
    # read a new frame
    _, frame = camera.read()
    
    # flip the frameq
    frame = cv2.flip(frame, 1)

   
    # add rectangle
    cv2.rectangle(frame, (200, 110), (450, 350), (240, 100, 0), 2)

    # get ROI
    roi = frame[110+2:350-2, 200+2:450-2]
    
    # parse BRG to RGB
    roi = cv2.cvtColor(roi, cv2.COLOR_BGR2RGB)
    

    # resize
    roi = cv2.resize(roi, (96,96))
    
    # predict!
    roi_X = np.expand_dims(roi, axis=0)

    predictions = model.predict(roi_X)
    type_1_pred, type_2_pred = predictions[0]

    # add text
    type_1_text = '{}: {}%'.format(class_names[0], int(type_1_pred*100))
    cv2.putText(frame, type_1_text, (70, 170), 
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (240, 240, 240), 2)

    # add text
    tipe_2_text = '{}: {}%'.format(class_names[1], int(type_2_pred*100))
    cv2.putText(frame, tipe_2_text, (70, 200), 
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (240, 240, 240), 2)

    

    # show the frame
    cv2.imshow("Test out", frame)

    key = cv2.waitKey(1)

    # quit camera if 'q' key is pressed
    if key & 0xFF == ord("q"):
        break

camera.release()
cv2.destroyAllWindows()